Add jest types to fix TSLint error 2593
TSLint can't resolve jest types unless this exists

Error:
TS2593: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha` and then add `jest` or `mocha` to the types field in your tsconfig.